name: notification

description: Discord notification

inputs:
  job-name:
    required: true
  status:
    required: true
  discord-webhook:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
